Set the Scala version and build classpath for Scala targets using the list of runfiles retrieved from Bazel.
JetBrains/bazel-bsp pull request #161
Opened 2022-02-18 11:18 UTC by odisseus

This seems to fix #127.

2022-02-18 13:30 UTC, abrams27 requested changes
looks really good, thanks!

please fix formatting, and tests are failing, also recently we introduced more flexible aspects labels resolving mechanism, so it would be nice to use it here as well

2022-02-18 14:29 UTC, abrams27 approved these changes

2022-02-18 14:47 UTC, lukaszwawrzyk approved these changes

2022-02-18 14:53 UTC, abrams27 commented
tests are still failing : (

2022-02-22 15:00 UTC, abrams27 commented
btw u can rebase for bazel 5.0.0

2022-03-07 10:49 UTC, abrams27 requested changes
I think that it will help

2022-03-07 10:49 UTC, abrams27 commented on server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspScalaTargetManager.java
> +            .map(path -> Uri.fromWorkspacePath(path, bazelData.getWorkspaceRoot()))
it causes that the path is resolved with workspace `"file:///home/runner/work/bazel-bsp/bazel-bsp/e2e/test-resources/sample-repo/external/io_bazel_rules_scala_scala_library/scala-library-2.12.8.jar"` (from e2e tests)

you should use `Uri.fromExecPath("exec-root://" + path, bazelData.getExecRoot())`

2022-03-07 13:08 UTC, abrams27 requested changes
ohh and the changelog!

2022-03-15 09:33 UTC, lukaszwawrzyk commented
Included in #147

2022-03-15 09:33 UTC, closed without merging