Filtering out transitive dependencies sources that are also root targets
JetBrains/bazel-bsp pull request #265
Opened 2022-07-05 13:45 UTC by sellophane

2022-07-05 14:54 UTC, abrams27 requested changes
tests are failing because we are expecting these sources now - just remove them from tests

2022-07-13 11:53 UTC, abrams27 approved these changes
please update the changelog + i think that we can get rid of `sourcesClasspath` field - @lukaszwawrzyk what do u thing?

2022-07-13 13:26 UTC, merged

2022-07-14 09:55 UTC, abrams27 commented on server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JavaLanguagePlugin.kt
> +            ?.jarsOrBuilderList
so how can we fix it?

2022-07-19 07:46 UTC, lukaszwawrzyk commented on server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JavaLanguagePlugin.kt
> +            ?.jarsOrBuilderList
Just use another field and concat result. Will happen on a followup pr.