Issue 108 tp
JetBrains/bazel-bsp pull request #276
Opened 2022-07-21 08:34 UTC by tpasternak

2022-07-21 09:32 UTC, abrams27 requested changes

2022-07-21 09:32 UTC, abrams27 commented on install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProvider.kt
> +            .longOpt("bazel workspace root dir")
```suggestion
            .longOpt("bazel_workspace")
```

2022-07-22 12:22 UTC, tpasternak commented
btw, `//e2e:BazelBspRemoteJdkTest` seems to be flaky

2022-07-22 12:34 UTC, tpasternak commented
Rebased and force-pushed on current master

2022-07-25 07:55 UTC, abrams27 reviewed
thanks a lot!

please update the changelog

2022-07-25 07:55 UTC, abrams27 commented on install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProvider.kt
> +            .desc("Path to directory where workspace is located.")
lets add what is the default - the `-d` and if `-d` is not specified then it's a pwd

2022-07-26 09:07 UTC, abrams27 requested changes

2022-07-26 09:12 UTC, abrams27 approved these changes

2022-07-26 09:42 UTC, merged