bugfix: Don't send classpath if jvmClasspathReceiver is set to true
JetBrains/bazel-bsp pull request #560
Opened 2024-04-24 12:29 UTC by tgodzik

It seems that somehow I missed adding it in the previous PR, which baffles me greatly.

This makes sure that if the client wants to only receive classpath via jvmClasspath request then it's done properly.

2024-04-25 14:42 UTC, agluszak requested changes

2024-04-25 14:42 UTC, agluszak commented on server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/ProjectSyncService.kt
> +  private var clientCapabilities = Optional.empty<BuildClientCapabilities>()
You probably want to use a [lateinit var](https://kotlinlang.org/docs/properties.html#late-initialized-properties-and-variables) here

2024-04-25 14:42 UTC, agluszak commented on e2e/src/main/kotlin/org/jetbrains/bsp/bazel/BazelBspScalaProjectTest.kt
> +  private val testClientClasspathReceiver = createTestkitClient(true)
```suggestion
  private val testClientClasspathReceiver = createTestkitClient(jvmClasspathReceiver = true)
```

2024-04-25 22:50 UTC, agluszak commented on server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/ProjectSyncService.kt
> +import kotlin.jvm.optionals.getOrDefault
```suggestion
```
No longer needed I guess?

2024-04-26 14:26 UTC, tgodzik commented
I am fixing tests separately as they were never run on CI. We can wait until those are passing if you want?

2024-05-07 09:28 UTC, tgodzik commented
@agluszak I rebased on master and the new tests pass, do you think it's good to merge?

2024-05-07 10:51 UTC, agluszak approved these changes

2024-05-07 10:51 UTC, merged